name: C/C++, ROS CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
        build:
                runs-on: ubuntu-18.04

                steps:
                - name : Chcekout to code
                  uses: actions/checkout@2
                - name: Install g++
                  run: sudo apt-get update && sudo apt-get install -y g++
                - name: Install CMake
                  run : |
                        wget -O cmake.sh https://github.com/Kitware/CMake/releases/download/v3.21.3/cmake-3.21.3-Linux-x86_64.sh
                        sudo sh cmake.sh --skip-lincese --prefix=/usr/local
                - name : Installing Dependencies
                  run : |
                        sudo apt-get update
                        apt-get -y install gcc gfortran patch wget pkg-config liblapack-dev libmetis-dev curl python3 python3-pip lsb-core
                        apt-get -y install libeigen3-dev coinor-libipopt-dev libncurses5-dev xterm

                - name: Set Up Third-party Directory
                  run: mkdir -p ./thirdparty
                  working-directory: ${{ github.workspace }}

                - name: Clone and Build Ipopt
                  run : |
                        git clone https://github.com/coin-or/Ipopt.git
                        cd thirdparty/Ipopt
                        mkdir -p build
                        cd build
                        ../configure
                        make -j4
                  working-directory: ${{ github.workspace }}
                - name : Clone and Build IFOPT
                  run : |
                        git clone https://github.com/ethz-adrl/ifopt.git
                        cd thirdparty/ifopt
                        mkdir -p build
                        cd build
                        cmake ..
                        make -j4
                        sudo make install
                  working-directory: ${{ github.workspace }}

                - name: Add ROS Repository
                  run : |
                        echo "deb http://packages.ros.org/ros/ubuntu bionic main" | sudo tee /etc/apt/sources.list.d/ros-melodic.list
                        curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -

                - name: Update apt
                  run : sudo apt update

                - name: Install ROS
                  run : |
                        sudo apt-get -y install ros-melodic-desktop-full

                - name: Set Up ROS Environment
                  run : |
                        echo "source /opt/ros/melodic/setup.bash" >> $HOME/.bashrc
                        source $HOME/.bashrc

                - name : Setting up Towr Dependencies
                  run  : apt-get install -y ros-melodic-xpp
                
                - name : 
                  uses: actions/checkout@v2
                  with:
                        repository: alexyskoutnev/towr_solo12 

                - name: Create Build Directory
                  run: mkdir build

                - name: Build
                  run: |
                        cd build
                        cmake -S ../ -DCMAKE_BUILD_TYPE=Release
                        make -j4  # Adjust the build command as needed
                        make install

                - name : Run Towr_SOLO12 Tests
                  run: |
                      bash /scripts/catkin_build/clear.sh
                      bash /scripts/catkin_build/build.sh
                      bash /scripts/cmake_build/clear.sh
                      bash /scripts/cmake_build/build.sh
                      bash /scripts/launch_rviz.sh

                - name : RUN Towr_SOLO12 OPTIMIZATION TEST
                  run : |
                        ./towr/build/towr-example

                - name: Push Changes (if tests passed)
                  if: ${{ success() }}
                  run: |
                        git config user.name "GitHub Actions"
                        git config user.email "<>"
                        git add .
                        git commit -m "Passed Building Test"
                        git push





